#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Simulation script for COMPONENT: main

cd /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38
verilator --cc --exe --Mdir /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//verilator_beh/verilator_obj -Wno-fatal -Wno-lint -sv -O3 /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/top.v /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//simulation/testbench_main_main.cpp /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//simulation/testbench_main_tb.v --top-module main_tb
if [ $? -ne 0 ]; then
   exit 1;
fi


ln -s /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output/ /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//verilator_beh/verilator_obj
make -C /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//verilator_beh/verilator_obj -j4 OPT_FAST="-O1 -fstrict-aliasing -march=native" -f Vmain_tb.mk Vmain_tb

/home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//verilator_beh/verilator_obj/Vmain_tb 2>&1 | tee /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_38/HLS_output//verilator_beh/main_verilator.log


