#!/bin/bash
(cd /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_32/panda-temp//temp-archive-dir-88cc-7fa9-7923-bb06; ar x /home/ubuntu/panda/lib/panda/libhls-cdiv_gcc7.a)  > /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_32/panda-temp/shell_output_2 2>&1 
