#!/bin/bash
(cd /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_32/panda-temp//temp-archive-dir-d077-2d2f-ecda-e560; ar x /home/ubuntu/panda/lib/panda/libsoftfloat_gcc7.a)  > /home/ubuntu/Desktop/SLIDE-x-Repository/SLIDE-x/SLIDE-x-AGGR/RECIPE_INT/bsort100/files/values_32/panda-temp/shell_output_6 2>&1 
